### ISSUE TITLE
[Refector] 정책 목록 공약 진행도 데이터 전송 방식 수정

### ISSUE THREAD

**Issue by si14444** [DEPthes/MJU-Council-Web#7]
## 🌏Summary
>  정책 목록 공약 진행도 데이터 전송 방식 수정

## ✔️ Task & Description
- [ ] #8

## 🐸 Reference
- 이행전 = 0
- 이행중 = 1
- 완료 = 2

{
    "check": true,
    "information": [
        {
            "id": 1,
            "title": "재수강 학점 A0 확대",
            "content": "블라블라블라",
            "progress": 0
        },
        {
            "id": 2,
            "title": "청소 꼼꼼히 하기",
            "content": "블라블라블라",
            "progress": 0
        }
    ],
    "message": null
}

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified PolicyListComponent to fetch and display policy data from the API, including the progress status.

You can review changes in this commit: https://github.com/lkilu6456546/DEPthes-MJU-Council-Web-7/commit/20aac0d5352bf2594c3703d95ae3c5d25b5b45aa.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
